version: "3.8"
services:
  minio:
    image: quay.io/minio/minio
    ports:
     - 9000:9000
     - 9001:9001
    environment:
     MINIO_ROOT_USER: minio
     MINIO_ROOT_PASSWORD: 123456789
    command: server /data --console-address ":9001"
